### ISSUE TITLE
Means of expediting publication

### ISSUE THREAD

**Issue by dchelimsky** [lsegal/rubydoc.info#41]
I just pushed a release of rspec and I've got a blog post sitting and waiting for my shiny new rdoc to appear on rubydoc.info :) Besides nudging somebody to perform some behind the scenes magic, it would be great if there was a hook I could use to nudge rubydoc.info directly so it knows to generate the docs for the latest release right away.

In the mean time ... nudge :)

**Comment by zapnap** [comment]
FYI, cleaning up issues here... Rubydoc uses RubyGems web hooks now, so gem docs should be auto-updated shortly after new gems are pushed.
