### ISSUE TITLE
GitHub Docs for ruby-net-ldap are completely broken

### ISSUE THREAD

**Issue by Ajedi32** [lsegal/rubydoc.info#94]
See http://www.rubydoc.info/github/ruby-ldap/ruby-net-ldap/master/frames

The documentation was visible in the past, but seems to be broken now. If you try to generate docs for that project using the "add project" feature, the page simply refreshes without the problem being solved.

Going to http://www.rubydoc.info/find/github?q=net-ldap and clicking the "reload this project" button there triggers a 500 error. (Also, no idea if this is related or not, but http://www.rubydoc.info/find/github?q=ruby-net-ldap throws a 500 as well.)

I discovered this problem while debugging a Chrome extension that hooks into rubydoc.info (<https://github.com/Ajedi32/rubydoc_github>), so it's quite possible that I may have triggered the problem by `POST`ing some unexpected data to `http://www.rubydoc.info/checkout`.

**Comment by zapnap** [comment]
We were having some temporary production server issues. Should be resolved now. Let me know if you run into any other problems and thanks for reporting the issue!
