### ISSUE TITLE
Github webhook returns 301

### ISSUE THREAD

**Issue by Xavdidtheshadow** [lsegal/rubydoc.info#98]
Per [these instructions](https://rubydoc.tenderapp.com/kb/git-integration/adding-a-rubydocinfo-post-receive-commit-hook-on-github) I added a webhook to our github project ([here](https://github.com/relateiq/ruby-sdk/)) with the following settings: 

* Payload url: `http://rubydoc.info/checkout`
* Content Type: `application/json`
* Secret: [none]
* `Just the 'push' event`
* :heavy_check_mark: `Active`

Upon pinging to test, Github receives the following response: 

```
Accept-Ranges: bytes
Age: 0
Connection: close
Date: Tue, 25 Aug 2015 20:40:40 GMT
Location: http://www.rubydoc.info/checkout
Server: Varnish
Via: 1.1 varnish
X-Cache-Status: MISS
X-Varnish: 1276015355
```

Am I doing something wrong, or is the issue on your end? The reason I set up a github project in the first place was that the rubygems hook wasn't updating the frame, but that's a separate issue (and I can file that as well). 

Thanks a bunch!

**Comment by zapnap** [comment]
Apologies for the delayed response! I believe this was an issue on our end, and has since been resolved.  If you're still seeing any weirdness, please reopen the issue. Thanks!
