### ISSUE TITLE
Frame doesn't update with new class

### ISSUE THREAD

**Issue by Xavdidtheshadow** [lsegal/rubydoc.info#99]
Upon releasing a new version of the gem ([commit](https://github.com/relateiq/ruby-sdk/commit/48a2ff625b9496fd82150162e41726d1742a7725)), rubydoc didn't seem to pick up the updated frame. 

The new class exists: http://www.rubydoc.info/gems/riq/RIQ/AccountProperties but isn't present in the frame or parent object.

**Comment by zapnap** [comment]
Looks like it's there now. Perhaps a temporary caching issue? I'll do a test push when I have a free moment and see if maybe our caches aren't being cleared appropriately.

**Comment by zapnap** [comment]
Will also take a look at your other issue soon. Thanks for reporting the issues!

**Comment by Xavdidtheshadow** [comment]
Sorry, I was unclear- The frame on the left of the page isn't updated. 

See rubygems: ![rubygems](http://i.imgur.com/qHS8ltH.png)

vs github: ![](http://i.imgur.com/p9Ctizp.png)

In both cases, the documented AccountProperties class appears, but it's not listed in the "table of contents" in the first image. The rubygems push was a couple of weeks ago (8/8), so it should have updated by now.

**Comment by lsegal** [comment]
I just cleared the cache on the class/various lists and it should be brought up to date now. Thanks for reporting, and sorry for the inconvenience!

**Comment by Xavdidtheshadow** [comment]
No problem! For reference, is that something that you'll have to do manually often, or was it more of a one time fluke?

**Comment by lsegal** [comment]
This happens automatically when new gems are discovered. My best guess is that something tripped up when caches were being invalidated since the main pages were but the list pages were not. This happens occasionally and is something we are looking into fixing.
